apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"5"},"creationTimestamp":"2019-01-13T14:19:59Z","generation":5,"labels":{"app":"production"},"name":"production","namespace":"default","resourceVersion":"2391930","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/production","uid":"4f1214dd-173e-11e9-9d6f-42010a840fdf"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"production"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"production"}},"spec":{"containers":[{"env":[{"name":"BOT_TOKEN","valueFrom":{"secretKeyRef":{"key":"prod.token","name":"bottoken"}}},{"name":"DATABASE_URL","valueFrom":{"secretKeyRef":{"key":"DATABASE_URL","name":"databasecredentials"}}},{"name":"MYSQL_DATABASE","valueFrom":{"secretKeyRef":{"key":"MYSQL_DATABASE","name":"databasecredentials"}}},{"name":"MYSQL_HOST","valueFrom":{"secretKeyRef":{"key":"MYSQL_HOST","name":"databasecredentials"}}},{"name":"MYSQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"MYSQL_PASSWORD","name":"databasecredentials"}}},{"name":"MYSQL_PORT","valueFrom":{"secretKeyRef":{"key":"MYSQL_PORT","name":"databasecredentials"}}},{"name":"MYSQL_USERNAME","valueFrom":{"secretKeyRef":{"key":"MYSQL_USERNAME","name":"databasecredentials"}}},{"name":"ADMIN_USERS","valueFrom":{"configMapKeyRef":{"key":"ADMIN_USERS","name":"production-config"}}},{"name":"FLUSH_INTERVAL","valueFrom":{"configMapKeyRef":{"key":"FLUSH_INTERVAL","name":"production-config"}}},{"name":"ICSBOT_ENV","value":"production"},{"name":"MIGRATIONS_DIR","valueFrom":{"configMapKeyRef":{"key":"MIGRATIONS_DIR","name":"production-config"}}},{"name":"PERSISTENCE","valueFrom":{"configMapKeyRef":{"key":"PERSISTENCE","name":"production-config"}}},{"name":"SQLITE_DB_PATH","valueFrom":{"configMapKeyRef":{"key":"SQLITE_DB_PATH","name":"production-config"}}},{"name":"TIMEZONE","valueFrom":{"configMapKeyRef":{"key":"TIMEZONE","name":"production-config"}}},{"name":"LOGGERS","valueFrom":{"configMapKeyRef":{"key":"LOGGERS","name":"production-config"}}},{"name":"GOOGLECLOUDLOGGER_PROJECT","valueFrom":{"configMapKeyRef":{"key":"GOOGLECLOUDLOGGER_PROJECT","name":"production-config"}}},{"name":"GOOGLECLOUDLOGGER_LOGNAME","valueFrom":{"configMapKeyRef":{"key":"GOOGLECLOUDLOGGER_LOGNAME","name":"production-config"}}},{"name":"GOOGLECLOUDLOGGER_RESOURCE_TYPE","valueFrom":{"configMapKeyRef":{"key":"GOOGLECLOUDLOGGER_RESOURCE_TYPE","name":"production-config"}}},{"name":"GOOGLECLOUDLOGGER_ENVIRONMENT","value":"production"}],"image":"eu.gcr.io/booming-octane-226319/icstelegrambot:1.8.1","imagePullPolicy":"Always","name":"icstelegrambot","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/assets","name":"assets-prod"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"assets-prod","persistentVolumeClaim":{"claimName":"assets-prod"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2019-01-13T14:19:59Z","lastUpdateTime":"2019-01-13T14:19:59Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2019-01-13T14:19:59Z","lastUpdateTime":"2019-01-13T22:18:27Z","message":"ReplicaSet \"production-75b5979799\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":5,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: 2019-01-13T14:19:59Z
  generation: 6
  labels:
    app: production
  name: production
  namespace: default
  resourceVersion: "2393676"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/production
  uid: 4f1214dd-173e-11e9-9d6f-42010a840fdf
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: production
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: production
    spec:
      containers:
      - env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              key: prod.token
              name: bottoken
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: databasecredentials
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: databasecredentials
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              key: MYSQL_HOST
              name: databasecredentials
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: databasecredentials
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
              key: MYSQL_PORT
              name: databasecredentials
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_USERNAME
              name: databasecredentials
        - name: ADMIN_USERS
          valueFrom:
            configMapKeyRef:
              key: ADMIN_USERS
              name: production-config
        - name: FLUSH_INTERVAL
          valueFrom:
            configMapKeyRef:
              key: FLUSH_INTERVAL
              name: production-config
        - name: ICSBOT_ENV
          value: production
        - name: MIGRATIONS_DIR
          valueFrom:
            configMapKeyRef:
              key: MIGRATIONS_DIR
              name: production-config
        - name: PERSISTENCE
          valueFrom:
            configMapKeyRef:
              key: PERSISTENCE
              name: production-config
        - name: SQLITE_DB_PATH
          valueFrom:
            configMapKeyRef:
              key: SQLITE_DB_PATH
              name: production-config
        - name: TIMEZONE
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: production-config
        - name: LOGGERS
          valueFrom:
            configMapKeyRef:
              key: LOGGERS
              name: production-config
        - name: GOOGLECLOUDLOGGER_PROJECT
          valueFrom:
            configMapKeyRef:
              key: GOOGLECLOUDLOGGER_PROJECT
              name: production-config
        - name: GOOGLECLOUDLOGGER_LOGNAME
          valueFrom:
            configMapKeyRef:
              key: GOOGLECLOUDLOGGER_LOGNAME
              name: production-config
        - name: GOOGLECLOUDLOGGER_RESOURCE_TYPE
          valueFrom:
            configMapKeyRef:
              key: GOOGLECLOUDLOGGER_RESOURCE_TYPE
              name: production-config
        - name: GOOGLECLOUDLOGGER_ENVIRONMENT
          value: production
        image: eu.gcr.io/booming-octane-226319/icstelegrambot:1.8.0
        imagePullPolicy: Always
        name: icstelegrambot
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /assets
          name: assets-prod
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: assets-prod
        persistentVolumeClaim:
          claimName: assets-prod
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-01-13T14:19:59Z
    lastUpdateTime: 2019-01-13T14:19:59Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-01-13T14:19:59Z
    lastUpdateTime: 2019-01-13T22:36:13Z
    message: ReplicaSet "production-948bfbd4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
